### ISSUE TITLE
Docker environment parameters: 'PUID' & 'PGID'

### ISSUE THREAD

**Issue by koelan** [jsavargas/telethon_downloader#46]
Hello there,

Thank you for such a great project.

I have a question regarding the setting of PUID and PGID in the 'docker-compose.yml'. I followed the example and my yml file is as follows. My issue is that the directory /var/www/telegram_download created by the docker container is always with 'root' user & group. I suppose it should be 'www-data' instead with PUID,PGID set to 33. Can you share with me what I have done wrong?

```
version: '3'
services:
  telethon_downloader:
    image: jsavargas/telethon_downloader
    container_name: telethon_downloader
    restart: unless-stopped
    network_mode: host
    environment:
      - 'PUID=33'
      - 'PGID=33'
      - 'TG_AUTHORIZED_USER_ID=xxxxxxxxx' #<telegram chat_id authorized>
      - 'TG_API_ID=xxxxxx'
      - 'TG_API_HASH=xxxxx'
      - 'TG_BOT_TOKEN=xxxxxx'
      - 'TZ=America/Santiago'
    volumes:
      - ./config:/config
      - ./download/torrent/watch:/watch
      - /var/www/telegram_download:/download
```
